development:
  adapter: postgresql
  encoding: unicode
  database: bark_development
  pool: 5
  username: donald
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bark_test
  pool: 5
  username: donald
  password:
